// GOSSIP ACTION TYPES

export const INITIATE_CREATE_GOSSIP = "INITIATE_CREATE_GOSSIP";
export const FINISH_CREATE_GOSSIP = "FINISH_CREATE_GOSSIP";
export const FAILED_CREATE_GOSSIP = "FAILED_CREATE_GOSSIP";

export const INITIATE_FETCH_GOSSIPS = "INITIATE_FETCH_GOSSIPS";
export const FINISH_FETCH_GOSSIPS = "FINISH_FETCH_GOSSIPS";
export const FAILED_FETCH_GOSSIPS = "FAILED_FETCH_GOSSIPS";

// QUESTION ACTION TYPES

export const INITIATE_CREATE_QUESTION = "INITIATE_CREATE_QUESTION";
export const FINISH_CREATE_QUESTION = "FINISH_CREATE_QUESTION";
export const FAILED_CREATE_QUESTION = "FAILED_CREATE_QUESTION";

export const INITIATE_FETCH_QUESTIONS = "INITIATE_FETCH_QUESTIONS";
export const FINISH_FETCH_QUESTIONS = "FINISH_FETCH_QUESTIONS";
export const FAILED_FETCH_QUESTIONS = "FAILED_FETCH_QUESTIONS";

// COMMENT ACTION types

export const CREATE_COMMENT_START = "CREATE_COMMENT_START";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";
